apiVersion: v1
kind: ConfigMap
metadata:
  name: fullstack-config
  namespace: fullstack
data:
  DB_HOST: mysql
  DB_PORT: "3306"
  DB_USER: root
  DB_NAME: fullstackdb
  NODE_ENV: production
  BACKEND_PORT: "5000"
